server:
  port: 8080

spring:
  datasource:
    username: root
    password: ufcr28BC
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: http://t-logistick.ru
      name: Т-логистик
    - url: https://itgit.ru
      name: АвтоВизор
#    - url: https://www.svetlovka.ru
#      name: Светловка
#    - url: https://www.lutherancathedral.ru
#      name: Кафедральный собор святых Петра и Павла
